### PR TITLE
my Gradient Boosting

### PR DESCRIPTION
**Pull request by jecampagne**
Hi, It is a very simple alternative to Random Forest and a modest contribution
1) I have put in JEC-modif.txt the conda install that I have done to install the machinary (the requierements.txt has been modified accordingly)
2) in tomo_challenge/classifiers/my_GB.py I have just implemented a simple Gradient Bossting classifier with the RF arguments and a new one
3) in example/my_GB.yaml  this is the way to call the classifier

Now I have managed to get some results:

- Using  'RIZ" bands:

o  n_classifiers=10, 3 bins
{‘SNR_ww’: 345.28152536963125, ‘SNR_3x2’: 1082.7750049866468, ‘FOM_3x2’: 31342.001304976227}

o  n_classifiers=10, 6 bins
{'SNR_ww': 348.4850751618621, 'SNR_3x2': 1379.712369940006, 'FOM_3x2': 58508.181229838374} 

o  n_classifiers=50, 6 bins
{'SNR_ww': 354.22777951535926, 'SNR_3x2': 1440.8869705962177, 'FOM_3x2': 13613.384073681802}

- Using 'GRIZ' bands

o  n_classifiers=50, 6 bins
{'SNR_ww': 365.6426860087726, 'SNR_3x2': 1507.5462299143685, 'FOM_3x2': 23845.36293198673}

What is strange is the FOM_3x2 behavior...
Now it may be nice to have some tools to 
1) get the contour plots which gives the FOM
2) a plot showing the redshift bins distributions

Anyhow it is a very nice tools I am very please to participate. Great job! hope that I have made constructive comments and adds

### CODE REVIEW

**Comment by joezuntz** [comment]
Thanks so much for our first entry!

I'll put together something to do the plots, that's a v good idea! And the FoM can certainly be noisy, especially at high scores - possibly seeing the n(z) values will help a little to understand the process.

**Comment by EiffL** [comment]
@joezuntz Are we sure we want to merge these PR? we could keep them open as a way to track submissions. People can keep updating their subimssion PRs, and we can have discussions about the proposed method in the PR thread

**Comment by jecampagne** [comment]
> @joezuntz Are we sure we want to merge these PR? we could keep them open as a way to track submissions. People can keep updating their subimssion PRs, and we can have discussions about the proposed method in the PR thread

Yes ! I think it is a good idea to get a mechanism to keep track & update

**Comment by joezuntz** [comment]
That's a good idea.  There's a revert button now, I'll try that.

**Pull request merged**
