### PR TITLE
Adds script to generate challenge data from Buzzard

### PR DESCRIPTION
**Pull request by EiffL**
This small PR just adapts the challenge data creation to be able to regenerate the data from Buzzard base catalog 

The parent catalog contains mcal simulated using TXPipe

The data generated can be found here:
```
/global/projecta/projectdirs/lsst/groups/WL/users/flanusse/tomo_challenge_buzzard
```

### CODE REVIEW

**Comment by joezuntz** [comment]
Is the u band available in buzzard?  Might be useful for comparison of 6 band case to 3/4 band.

**Comment by EiffL** [comment]
Yeah,,, I think it is, but let me check.
I removed it because I wanted to be minimal in terms of how much data from Buzzard we were using, hoping that this way, we would get the go ahead from the authors to make it public.

**Comment by EiffL** [comment]
yep, we can use
```
Saving mag_u
Saving mag_g
Saving mag_r
Saving mag_i
Saving mag_z
Saving mag_y
```
if we want, it's included in Buzzard

**Comment by EiffL** [comment]
So here is a colour comparison between DC2 and Buzzard obtained with these scripts:
image
image
with `m = ( training_data['r'] > 20.) & (training_data['r'] < 24.)`

The redshift distributions end up being slightly different, shorter tail as high redshift, but otherwise everything looks ok to me

**Comment by EiffL** [comment]
image

**Pull request merged**
